name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: commands => run maven
        run: |
          pwd
          ls -l
          cd $GITHUB_WORKSPACE/pitufos
          echo "---------------"
          ls -l
          df -h
          set
          mvn -q clean compile
#      - name: Run test suite
#        run: docker-compose -f docker/docker-compose.yaml exec -T app bash scripts/build.sh
#      - name: Upload coverage report
#        uses: codecov/codecov-action@v2
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name : check test
        run : |
          cd $GITHUB_WORKSPACE/pitufos
          mvn -q clean compile test
  package:
    runs-on: ubuntu-20.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: run maven
        run: mvn clean compile
#      - name: Package
#        run: docker-compose -f docker/docker-compose.yaml exec -T app bash scripts/package.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/pitufos-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
